### ISSUE TITLE
Add supporting markdown files

### ISSUE THREAD

**Issue by emdupre** [poldrack/poldracklab-staging.github.io#1]
It looks like the main branch contains a built version of the site ; i.e., it's missing the supporting markdown and quatro-markdown files noted in `_quarto.yml`.

Would you be able to upload the original, supporting files -- possibly on another branch ? We could then add a github action to build those and deploy to a gh-pages branch for rendering. 

I think it would be easier to edit those markdown files than the generated HTML !

**Comment by poldrack** [comment]
thanks, sorry I forgot to add those! just pushed a commit that contains them (in the main branch - that's where I meant to put them, just forgot). would be great to add a github action, but building the files is nontrivial since it pulls info from my academicdb database which requires credentials. we should discuss whether there is a better way to do it.

**Comment by poldrack** [comment]
BTW - I'm working on the automated build right now.

**Comment by emdupre** [comment]
Ah perfect, thanks ! I can resolve this issue and open a new one if we want to better track that 🚀
